function title = create_title(obj, parent, title_str)
% Create a simple title object for the GUI
%
% Inputs:
% obj          = AddRecordsGUI object
% parent       = Parent GUI object for the title
% title_str    = String for the title
%
% Outputs
% title        = GUI object for the title

title = uicontrol ( ...
    'Parent', parent, ...
    'Style', 'text', ...
    'String', title_str, ...
    'FontSize', obj.TITLE_FONTSIZE, ...            
    'BackgroundColor', obj.TITLE_BKG_CLR, ...
    'ForegroundColor', obj.TITLE_CLR, ...
    'FontWeight', 'bold');

end
