function label = create_label(obj, parent, name, tooltip)
% Create a simple label object for the GUI
%
% Inputs:
% obj          = AddRecordsGUI object
% parent       = Parent GUI object for the label
% name         = string Label for the field
% tooltip      = string tooltip for the field
%
% Outputs
% title        = GUI object for the label

label = uicontrol ( ...
    'Parent', parent, ...
    'Style', 'text', ...
    'String', name, ...
    'FontSize', obj.LABEL_FONTSIZE, ...                             ...
    'BackgroundColor', obj.LABEL_BKG_CLR, ...
    'TooltipString', [obj.LABEL_TOOL_TIP_START tooltip obj.LABEL_TOOL_TIP_END], ...
    'ForegroundColor', obj.LABEL_CLR, ...
    'FontWeight', 'bold');

end
